// Copyright (C) 2022 Daniel T. McGinnis
// SPDX-License-Identifier: BSL-1.0

#ifndef CMP_CORE_CONFIG_HPP_INCLUDED
#define CMP_CORE_CONFIG_HPP_INCLUDED

#ifndef CMP_CONFIG_IS_STATIC
#   define CMP_CONFIG_IS_STATIC false
#endif // CMP_CONFIG_IS_STATIC

#ifndef CMP_CONFIG_IS_DYNAMIC
#   define CMP_CONFIG_IS_DYNAMIC false
#endif // CMP_CONFIG_IS_DYNAMIC

#define CMP_CONFIG_IS_BUILDING CMP_CONFIG_IS_STATIC || CMP_CONFIG_IS_DYNAMIC

#ifndef CMP_CONFIG_LTO_REQUESTED
#   define CMP_CONFIG_LTO_REQUESTED true
#endif // CMP_CONFIG_LTO_REQUESTED

#ifndef CMP_CONFIG_LTO_ENABLED
#   define CMP_CONFIG_LTO_ENABLED false
#endif // CMP_CONFIG_LTO_ENABLED

#ifndef CMP_CONFIG_HEADER_ONLY
#   define CMP_CONFIG_HEADER_ONLY false
#endif // CMP_CONFIG_HEADER_ONLY

#ifndef CMP_CONFIG_DEFAULT_BUFFER_CAPACITY
#   define CMP_CONFIG_DEFAULT_BUFFER_CAPACITY 1024
#endif // CMP_CONFIG_DEFAULT_BUFFER_CAPACITY

#ifndef CMP_CONFIG_DEFAULT_STDOUT_BUFFER_CAPACITY
#   define CMP_CONFIG_DEFAULT_STDOUT_BUFFER_CAPACITY CMP_CONFIG_DEFAULT_BUFFER_CAPACITY
#endif // CMP_CONFIG_DEFAULT_STDOUT_BUFFER_CAPACITY

#ifndef CMP_CONFIG_DEFAULT_STDERR_BUFFER_CAPACITY
#   define CMP_CONFIG_DEFAULT_STDERR_BUFFER_CAPACITY CMP_CONFIG_DEFAULT_BUFFER_CAPACITY
#endif // CMP_CONFIG_DEFAULT_STDERR_BUFFER_CAPACITY

#ifndef CMP_CONFIG_DEFAULT_STDIN_BUFFER_CAPACITY
#   define CMP_CONFIG_DEFAULT_STDIN_BUFFER_CAPACITY CMP_CONFIG_DEFAULT_BUFFER_CAPACITY
#endif // CMP_CONFIG_DEFAULT_STDIN_BUFFER_CAPACITY

#ifndef CMP_CONFIG_IO_PACKAGE_EXCLUDED
#   define CMP_CONFIG_IO_PACKAGE_EXCLUDED false
#endif // CMP_CONFIG_IO_PACKAGE_EXCLUDED

#define CMP_LIBRARY_NAME
#if CMP_CONFIG_IS_DYNAMIC == true
#   if __has_include(<cmp_export.hpp>)
#      include <cmp_export.hpp>
#      define CMP_LIBRARY_NAME CMP_EXPORT
#   endif
#endif

#endif // CMP_CORE_CONFIG_HPP_INCLUDED
